#!/usr/bin/ruby

require 'optimist'
require 'open3'

class Post
  def self.helper(mode, x)
    command = "curl -i -F'#{mode}=#{x}' http://0x0.st"
    Open3.popen2(command + ' 2> /dev/null') do |i,o|
      o.gets(nil).lines
        .map(&:chomp)
        .map { |l| l.split(': ') }
    end
  end

  def self.file(file)
    Post.helper('file', '@' + file)
  end

  def self.link(link)
    Post.helper('url', link)
  end
end

def response(x)
  status = x[0][0].split[1]
  headers = x[1..].take_while { |a| a.size > 0 }
  body = x[headers.size + 2 ..].join("\n")

  [['Status', status]] + headers+ [['Body', body]]
end

response(Post.file(ARGV[0]))
  .each { |k,v| puts k + ': ' + v }
