(scheme
 (chicken base)
 (chicken bitwise)
 (chicken blob)
 (chicken condition)
 (chicken file)
 (chicken fixnum)
 (chicken flonum)
 (chicken format)
 (chicken gc)
 (chicken irregex)
 (chicken keyword)
 (chicken platform)
 (chicken plist)
 (chicken pretty-print)
 (chicken random)
 (chicken sort)
 (chicken string)
 (chicken syntax)
 (chicken time)
 (chicken file posix)
 (chicken time posix)
 (chicken continuation)
 (chicken errno)
 (chicken eval)
 (chicken io)
 (chicken load)
 (chicken locative)
 (chicken memory)
 (chicken memory representation)
 (chicken port)
 (chicken module)
 (chicken pathname)
 (chicken process-context)
 (chicken process-context posix)
 (chicken read-syntax)
 (chicken process)
 (chicken process signal)
 (chicken repl)
 (chicken tcp)
 srfi-4)
